### ISSUE TITLE
Running 01-single-gpu/train_llm.py causes an error using tatsu-lab/alpaca dataset 

### ISSUE THREAD

**Issue by NlsnBoa** [LambdaLabsML/distributed-training-guide#43]
### I followed the directions on the ReadMe and ran the first script for 01-single-gpu and received this output:

---

/home/ubuntu/distributed-training-guide/venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Downloading readme: 100%|████████████████████████████████████████████████████| 7.47k/7.47k [00:00<00:00, 32.8MB/s]
Downloading data:   0%|                                                               | 0.00/24.2M [00:00<?, ?B/s]Traceback (most recent call last):
  File "/home/ubuntu/distributed-training-guide/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/home/ubuntu/distributed-training-guide/venv/lib/python3.10/site-packages/urllib3/connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

**Comment by NlsnBoa** [comment]
It worked the next time I tried and for some reason it worked.
